gen_options:
  save: True
  saveeps: False ## Saves figures both in .png and .eps formats (False=only .png)
  dir_save: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/model_figs/"
  #  dir_save_figs: '/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-Fernando-ML-DL/model_figs/SSalldirs-3HL/'
  dim: "2D" # by default the BC is applied in plane (1-2) == (x-y)-.
  nirun: 2 # number of cases VPSC/IRUNs, used in statisticalPlots (i.e. src/plot_res_statistical.py)-.
  irun: 3 #'random' #"random" # 'random' or int. How select the VPSC's/IRUN's cases from dataset-.
  nnn: 10 # number of NN to be used in uncertainty determination-.
  quart: 2 # uncertaninty interval of 95%-.
  emax: 10 # xmax for epsilon-bases plots

dataset:
  path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2022/2-Automated-Elastic/10-Databases/db3/"
  #  path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2022/2-Automated-Elastic/10-Databases/db3-wTex/"
  #  name: 'db3-PS-resc.csv'
  #  name: 'db3-SS.csv'
  #  name: "db3-SSb.csv"
  #  name: 'db3-SSalldirs.csv'
  #  name: 'db3-SSalldirs_2024-12-11_eps10.csv'
  #  name: 'db3-SSalldirs-wIni.csv'
  #  name: "db3-SSalldirs_Eps10.csv"
  #  name: "db3-SSalldirs-SO_Eps10.csv"
  #  name: 'db3-CFMORn1-90deg-resc.csv'
  #  name: 'db3-CFMORn1-90deg-resc-Eps10-20240412.csv'
  name: "db3-CFMORn1-90deg-resc-Eps10-20240414.csv"
  # name: "db3-CFMORn1-90deg-resc-SO-Eps10.csv"
  #  name: 'db3-TGT-CFMORn1-90deg-resc-Eps10-20240826.csv'
  #  name: 'db3-SZModel1-str75-100.csv'
  #  name: 'db3-SZModel1-str100-130.csv'
  #  name: 'db3-SZModel1-str130-160.csv'

model:
  #  path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/models/MLP-20240312_170406/" ## db_train : db3-SSalldirs
  path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/models/MLP-_-20240329_104524/" ## db_train : db3-SSallirsPScst
  #  path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/models/MLP-_-20240615_224008/" ## db_train : db3-SSallirsPScst with TexIniSDxSDy4
  #  path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/models/MLP-_-20240831_110257_TGT/" ## db_train : db3-TGT-SSallirsPScst
  # path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/models/MLP-_-20250207_180134/" ## db_train : db3-SSallirsPS-wTexIniEps4
  # path: "/Users/nestorcerpa/ProgramsMBP/1-MyCodes/Anisotropy/2023/3-AnisNew-ML-DL/models/MLP-_-20250325_164913/" ## db_train : db3-SSalldirsPScst-SO-TexIniEps10
  name: "dlModelWithoutHyperOpt_torch.pt"

scaler:
  feat: "featScaler.pkl"
  targ: "targScaler.pkl"
##  feat: 'scaler_feat.pkl' # @1
##  targ: 'scaler_targ.pkl' # @1
