gen_options:
  save_figs: True
  dir_save_figs: '/Users/Fernando/temp/'
  dim: '2D'  # by default the BC is applied in plane (1-2) == (x-y)-.
  irun: 'random'
  
dataset:
  path: '/Users/Fernando/temp/' 
  name: 'db3-CFMORn1-90deg-resc.csv' 

model:
  path: '/Users/Fernando/temp/models/' 
  name: 'dlModelWithoutHyperOpt.pt'

scaler:
  feat: 'scaler_feat.pkl'
  targ: 'scaler_targ.pkl'

